[versions]
kotlin = "2.0.0"
koin = "4.0.0"

[libraries]
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
